name: Build and Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if .nvmrc exists
        id: nvm-check
        run: |
          if [ -f .nvmrc ]; then
            echo "version=$(cat .nvmrc)" >> $GITHUB_OUTPUT
          else
            echo "version=18" >> $GITHUB_OUTPUT
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvm-check.outputs.version }}
          cache: 'yarn' # Changed to optimize and cache Yarn dependencies

      - name: Install dependencies
        run: yarn install --frozen-lockfile # Ensures the build uses your exact yarn.lock

      - name: Run build
        run: yarn build # Switched to Yarn

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
